# Linear Classifiers: The Coefficients
The conceptual framework behind logistic regression and SVMs

In [1]:
# pip3 install numpy
import numpy as np

### Dot Products

In [2]:
x = np.arange(3)
print(x)
print(x.shape)
print(type(x))

[0 1 2]
(3,)
<class 'numpy.ndarray'>


In [3]:
y = np.arange(3, 6)
print(y)
print(y.shape)
print(type(y))

[3 4 5]
(3,)
<class 'numpy.ndarray'>


In [4]:
# Displaying Dot Product
print(x*y)
print(x*y.shape)
print(type(x*y))

[ 0  4 10]
[0 3 6]
<class 'numpy.ndarray'>


In [5]:
# Displaying Dot Product Summation
print(np.sum(x*y))
print(np.sum(x*y).shape)
print(type(np.sum(x*y)))

# Creating new line to demostrate the 2 diffrent ways
# that Dot Product summation can be shown
print('\n')

# Displaying alternative method
# x@y is called the dot product of x and y
print(x@y)
print((x@y).shape)
print(type(x@y))

14
()
<class 'numpy.int64'>


14
()
<class 'numpy.int64'>


### Linear Classifier Prediction
- Written as: raw model output = coeficients (dot) features + intercept
- Linear classifier prediction: compute  raw model output, check the **sign**
  - If positive, predict one class
  - If negative, predict the other class


### Loss Functions
The loss function is a penalty score that tells us how well (or, to be precise, how poorly) the model is doing on the training data. We can think of the "fit" function as running code that minimizes the loss. Note that the score function provided by scikit-learn isn't necessarily the same thing as the loss function. The loss is used to fit the model on the data, and the score is used to see how well we're doing. It's intuitive that these would be the same, and they often are, but you should be aware that this isn't guaranteed.

In [6]:
# minimizing a loss
# pip3 install scipy
from scipy.optimize import minimize

minimize(np.square, 0).x

# It's correct because something squared can only be zero or more, 
# thus, its smallest possible value is attained when x=0.

array([0.])

In [7]:
# Another example of minimizing a loss
from scipy.optimize import minimize

minimize(np.square, 2).x

array([-1.88846401e-08])